---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Create CLC SRN Server
      clc_server:
        name: "shtst"
        template: ubuntu-14-64
        count: 1
        group: "SHGRP"
        location: "CA3"
      register: clc
    - debug: var=clc
